### Uncomment the custom rules section below to:
### - pull preferentially from the ingest results.
### See README.md for more information

#custom_rules:
#    - build-configs/state_focused/copy_from_ingest.smk
builds: 'N450'
custom_subsample:
    N450:
        defaults:
            exclude_ambiguous_dates_by: year  
        samples:
            state:
                query: division == "Texas"
                max_sequences: 2000
                min_length: 400
                min_date: "2023"
                exclude:
                    - defaults/dropped_strains.txt
            continental:
                query: division != "Texas" & region == "North America"
                max_sequences: 2000
                min_length: 400
                min_date: "2023"
                exclude:
                    - defaults/dropped_strains.txt
            global:
                query: region != "North America"
                max_sequences: 1000
                min_length: 400
                min_date: "2023"
                include:
                    - defaults/include_strains_genome.txt
                exclude:
                    - defaults/dropped_strains.txt